### ISSUE TITLE
能否提供批量删除功能？

### ISSUE THREAD

**Issue by 60999** [sunhanaix/SyncXiaomiCloud#1]
我经常是这样使用的，将网盘同步到电脑上，电脑上数据备份到移动硬盘，NAS。
删除全部云端数据腾空空间。

**Comment by sunhanaix** [comment]
2023.8.29更新，增加了是否删除云空间的已经下载照片/视频的可选项。默认为不删除，如需要删除，修改config.py的down_and_del=True
