### ISSUE TITLE
能否部署到Docker中？

### ISSUE THREAD

**Issue by WuhanSy** [sunhanaix/SyncXiaomiCloud#3]
是否提供Docker方式部署？

**Comment by sunhanaix** [comment]
目前做了arm64和x64的两个image，
可以docker pull sunbeat/sync_xiaomi:x64
或者docker pull sunbeat/sync_xiaomi:arm64
进行介质拉取。
然后docker run -v /xx/config.py:/app/config.py   \
-v /xx/docker_xiaomi:/app/xiaomi \
sunbeat/sync_xiaomi:x64

其中/xx/config.py里面修改成你的配置文件
/xx/docker_xiaomi修改成你要存放数据的目录
